[build]
  command = "npm run build"
  publish = ".next"
  environment = { 
    NODE_VERSION = "18",
    NEXT_PUBLIC_BASE_URL = "https://okama.ca"
  }

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: Redirects (Netlify Forms & Functions require POST endpoints)
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
